//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_Database_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudioCountry
    {
        public int ID { get; set; }
        public int StudioID { get; set; }
        public int CountryID { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Studios Studios { get; set; }
    }
}
